apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nuget-semver
  annotations:
    github.com/project-slug: snyk/nuget-semver
    github.com/team-slug: snyk/engines_sca-scanners
spec:
  type: external-library
  lifecycle: "-"
  owner: sca-scanners
