version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/node:24.18

commands:
  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: Install dependencies
          command: npm install
  run_test:
    steps:
      - run:
          name: Test
          command: npm test

jobs:
  security-scans:
    <<: *defaults
    steps:
      - checkout
      - install_deps
      - prodsec/security_scans:
          mode: auto
          open-source-additional-arguments: --exclude=test
          iac-scan: disabled

  test:
    <<: *defaults
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - install_deps
      - run_test

  release:
    <<: *defaults
    steps:
      - checkout
      - install_deps
      - run:
          name: Release
          command: |
            export NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            npx semantic-release@25.0.5

workflows:
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
            - prodsec-orb-runtime
          channel: snyk-vuln-alerts-sca-scanners
          filters:
            branches:
              ignore:
                - main
      - security-scans:
          name: Security Scans
          context:
            - engines_sca-scanners
            - nodejs-install
            - prodsec-orb-runtime
      - test:
          name: Test Node << matrix.node-version >>
          context: nodejs-install
          matrix:
            parameters:
              node-version: ["22.23", "24.18", "26.4"]
          filters:
            branches:
              ignore:
                - main
      - release:
          name: Release
          context:
            - nodejs-install
            - github-release
          filters:
            branches:
              only:
                - main
